### ISSUE TITLE
Add Support for Latest ODL - Beryllium

### ISSUE THREAD

**Issue by mafernando** [projectjellyfish/jellyfish-odl#3]
### Expected Behavior

Users should be able to add a vRouter product from the marketplace and use that to view firewall rules as well as add/remove custom rules against the latest ODL release, Beryllium. 
### Current Behavior

The current version of ODL this module supports is Lithium (3rd release). The latest ODL, Beryllium (4th release), has introduced changes to the way that YANG models are parsed and to the way API endpoints are constructed. 
### Possible Solution

Since backwards compatibility isn't a priority at the moment, we can maintain two branches of this extension. The Li branch will contain the existing JF/ODL demo code against the Li release and the Be branch will contain new JF/ODL code written against the latest ODL Be release.
### Steps to Reproduce (for bugs)

N/A
### Context

Investigating opportunities to develop SDN functionality through Jellyfish using ODL. Since ODL exists both in open source and commercial formats, the functionality developed on top of ODL can be extended across multiple environments. 
### Your Environment
- Version used: 0.0.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Ubuntu 14.04 LTS

**Comment by mafernando** [comment]
**ToDo:**
- [x] Decouple `order_questions` & `service_class` from `ProductType`
  - [x] Create `server` `Product` with `order_questions` & `service_class`
  - [x] Remove `order_questions` & `service_class` from `server` `ProductType`
- [x] Verify compatibility with the latest JF core (refactored cart and front end)
- [x] Add `Enable Video Policy` button
- [x] Add `Disable Video Policy` button
- [x] Verify REST to/from lab ODL instance with updated code ODL - Li
- [x] Verify REST to/from lab ODL instance with updated code ODL - Be
- [x] Verify Dockerfile/Compose deployment in lab w/ connectivity to ODL 
-  ~~Update `version.rb`~~
- [x] Create `demo/odl-be` branch
- ~~Rename `demo/odl` branch to `demo/odl-li`~~ 
- ~~Update `develop` branch~~
- ~~Update `master` branch~~

**NiceToHave:**
- Investigate LOE for implementing a form that allows you assign the addition/removal of a set of firewall rules to a dynamically generated button

**Comment by mafernando** [comment]
So, quick update. I was able to connect to the CSN lab using RDP yesterday and access the different demo VMs we'll be using. 
The current JF is quite a few commits ahead of the fork that we used for ODL and as a consequence the Dockerfile/compose for the latest JF doesn't deploy with ODL (or Demo Extension).
Am seeing:

```
Removing intermediate container bc8b71a6e72a
Step 15 : RUN DB_ADAPTER=nulldb bundle exec rake assets:precompile
 ---> Running in 37a0d4384aec
rake aborted!
No such middleware to insert before: ActionDispatch::Static
/usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb:125:in `assert_index'
/usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb:88:in `insert'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/configuration.rb:68:in `block in merge_into'
```

in the Docker build logs. I suspect it might be an issue with how the gem is setup, but not sure.

I spent a large chunk of yesterday and this morning trying to get the Dockerfile/compose working with the latest JF + ODL, but given our time constraints I don’t think I can afford to figure out that piece atm.

Am going to try at it until noon my time and then spend the rest of today implementing the discussed barebones implementation on top of the existing fork. 

Not ideal, but I think its a compromise we can revisit later if needed.

**Comment by mafernando** [comment]
Looks like I was able to get the latest JF working with Dockerfile/compose that has working DB connectivity. 

Some of the issues deploying JF to production after moving the front-end build process to `rails-assets` seem to be affecting the docker environment that gets spun up internally when the app container is deployed. 

Since this extension isn't intended to run in production, I refitted the Dockefile/compose to run in development to get everything working. 

I went ahead and cut a branch with those changes that will be used as the base for all the ODL Be work at https://github.com/mafernando/api/tree/demo/odl-be.

**Comment by mafernando** [comment]
To keep things consolidated, am developing on forks and then will PR up to the PJ repos:
- API: https://github.com/mafernando/api/tree/demo/odl-be
- Demo Extension: https://github.com/mafernando/jellyfish-demo/tree/demo/odl-be
- ODL Extension: https://github.com/mafernando/jellyfish-odl/tree/demo/odl-be

**Comment by mafernando** [comment]
Update for today: I managed to get the enable/disable video policy button working against ODL Li connected to a 3.x vRouter and then got that deployed on a CSN lab VM using Docker.
Met with Lundberg this morning to review progress and received refinement feedback that I'm going to work through today:
- [x] Refactor enable/disable video policy to not use update REST calls (they are too laggy to demo)
- [x] Replace the ODL Version provider question with a Product question to specify the version of the vRouter (this is tied underlying YANG models the api endpoints are built against)
- [x] Add text field to router product to specify the name node associated with the router on the ODL controller
  - NiceToHave: Make this a dynamic drop down that is popualted using the JSON response from REST call to ODL to get connected network devices
- [x] Build out ODL REST Calls against vRouter 4.x endpoints
- Nice to have: hookup JF-ODL-AWS demo to provision against the latest JF/ODL code

**Comment by mafernando** [comment]
ODL Development Week 2 ToDoList:
- [x] Use service name from ordering to supply the router name used in the internal API calls to ODL (since we don't have order questions atm)
- [x] Revisit AWS demo and hookup the latest AWS JF Extension to ODL 
- ~~Review LOE for having policies that consist of multiple rules + UX to support that~~

**Comment by mafernando** [comment]
**BSC Enable/Disable Video Policy Demo Branch:**
- https://github.com/mafernando/api/tree/demo/odl-bsc
- https://github.com/mafernando/jellyfish-demo/tree/demo/odl-bsc
- https://github.com/mafernando/jellyfish-odl/tree/demo/odl-bsc

**ODL AWS Firewall Provisioning Demo Branch:**
- https://github.com/mafernando/api/tree/demo/odl-aws
- https://github.com/mafernando/jellyfish-demo/tree/demo/odl-aws
- https://github.com/mafernando/jellyfish-odl/tree/demo/odl-aws
- https://github.com/mafernando/jellyfish-aws/tree/demo/odl-aws

**Comment by mafernando** [comment]
Managed to wrap up the bare bones BSC demo and have that cut against the demo/odl-bsc branches.
Am working to get the old AWS provisioning demo working again on the latest JF.
After that will look at adding a dynamic number of rules to the firewall policy which will require some custom form field development inside of the odl extension. 
Not sure how that will pan out yet, but will tackle it when we get there. http://angular-formly.com/#/example/other/multi-input seems like a promising option.

**Comment by mafernando** [comment]
After chatting with Stack, looks like the dynamic rule policy thing could be achieved using http://angular-formly.com/#/example/advanced/repeating-section. Implementing it in JF/ODL is complex, so it'll take some time to parse out how stuff is working.

**Comment by mafernando** [comment]
Code has been pushed to appropriate branches and demo work has been deployed in lab environment successfully. Closing this ticket as the original issue has been resolved.
